// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import product "github.com/ngdlong91/funtech/cmd/gin/pkg/product"

// ProductServer is an autogenerated mock type for the ProductServer type
type ProductServer struct {
	mock.Mock
}

// DoPurchase provides a mock function with given fields: _a0, _a1
func (_m *ProductServer) DoPurchase(_a0 context.Context, _a1 *product.PurchaseRequest) (*product.PurchaseResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *product.PurchaseResponse
	if rf, ok := ret.Get(0).(func(context.Context, *product.PurchaseRequest) *product.PurchaseResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.PurchaseResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *product.PurchaseRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
