// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import dto "github.com/ngdlong91/funtech/cmd/gin/dto"
import mock "github.com/stretchr/testify/mock"

// ProductRepo is an autogenerated mock type for the ProductRepo type
type ProductRepo struct {
	mock.Mock
}

// Insert provides a mock function with given fields: quantity
func (_m *ProductRepo) Insert(quantity int) error {
	ret := _m.Called(quantity)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Purchase provides a mock function with given fields: id, quantity
func (_m *ProductRepo) Purchase(id int, quantity int) (dto.Product, error) {
	ret := _m.Called(id, quantity)

	var r0 dto.Product
	if rf, ok := ret.Get(0).(func(int, int) dto.Product); ok {
		r0 = rf(id, quantity)
	} else {
		r0 = ret.Get(0).(dto.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(id, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Select provides a mock function with given fields: id
func (_m *ProductRepo) Select(id int) (dto.Product, error) {
	ret := _m.Called(id)

	var r0 dto.Product
	if rf, ok := ret.Get(0).(func(int) dto.Product); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(dto.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
