// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Cancel provides a mock function with given fields:
func (_m *Service) Cancel() {
	_m.Called()
}

// Detail provides a mock function with given fields:
func (_m *Service) Detail() {
	_m.Called()
}

// List provides a mock function with given fields:
func (_m *Service) List() {
	_m.Called()
}

// Purchase provides a mock function with given fields:
func (_m *Service) Purchase() {
	_m.Called()
}
